# Generated by Django 4.1 on 2022-08-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='auth_token',
            new_name='auth_token_check',
        ),
    ]
