# Generated by Django 4.1 on 2022-08-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_auth_token_customuser_auth_token_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='auth_token_check',
            new_name='auth_token',
        ),
    ]
