# Generated by Django 4.1 on 2022-08-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_auth_token_customuser_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('b', 'Block')], default='a', max_length=1),
        ),
    ]
