# Generated by Django 4.1 on 2022-08-12 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipes_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={},
        ),
    ]
